services:
  db:
    image: postgres:17-alpine
    container_name: impenetrable-db
    environment:
      POSTGRES_USER: impenetrable
      POSTGRES_PASSWORD: password
      POSTGRES_DB: impenetrable_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
