import { z } from "zod";
import { UserRoleSchema } from "./common";

/**
 * Unified User Entity - matches DER §8.1
 *
 * Single table for all user types (tourist, entrepreneur, admin)
 * - Tourist: alias is required, email is null
 * - Entrepreneur/Admin: email is required, alias is null
 */
export const UserSchema = z.object({
  zzz_id: z.string().uuid(),
  zzz_alias: z.string().max(50).nullable(), // Tourists only
  zzz_email: z.string().email().nullable(), // Admin/Entrepreneur only
  zzz_first_name: z.string().max(100).nullable(),
  zzz_last_name: z.string().max(100).nullable(),
  zzz_whatsapp: z.string().nullable(),
  zzz_user_type: UserRoleSchema,
  zzz_failed_login_attempts: z.number().int().default(0),
  zzz_locked_until: z.date().nullable(),
  zzz_last_login_at: z.date().nullable(),
  zzz_is_active: z.boolean().default(true),
  zzz_created_at: z.date(),
});

// TypeScript interface inferred from schema
export type User = z.infer<typeof UserSchema>;

/**
 * Schema for creating a new user (mobile login for tourists)
 * - id and timestamps are generated by the backend
 */
export const CreateUserSchema = UserSchema.omit({
  zzz_id: true,
  zzz_failed_login_attempts: true,
  zzz_locked_until: true,
  zzz_last_login_at: true,
  zzz_is_active: true,
  zzz_created_at: true,
});

export type CreateUserInput = z.infer<typeof CreateUserSchema>;

/**
 * Schema for updating user profile
 */
export const UpdateUserSchema = CreateUserSchema.partial();

export type UpdateUserInput = z.infer<typeof UpdateUserSchema>;
